config/routes.rb
Rails.application.routes.draw do
  

   
  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  root 'welcome#index'
  get 'welcome/index'
  get 'game_page/index'
  resources :players
  resources :scores
  
  post 'scores/create' => 'scores#create'
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Battleship::Application.routes.draw do
  get 'auth/google_oauth2/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
    has_many :ships
    has_many :scores
    
end

app/models/score.rb
class Score < ApplicationRecord
   belongs_to :player, required: false
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/game_page_controller.rb
class GamePageController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
    
    def new
        @player = Player.new
    end
    
    def show
        @player = Player.find(params[:id])
    end
    
    def create
        #render plain: params[:article].inspect
        @player = Player.new(player_params)
        
        
        if @player.save
    
            redirect_to game_page_index_url
        else
            render 'new'
        end
    end
    
     def edit
        @player =  Player.find(params[:id])
    end
    def update
        @player = Player.find(params[:id])
        if @player.update()
        redirect_to @article
        else
        render 'edit'
        end
    end
    
    private
        def player_params
            params.require(:player).permit(:userName,:password)
        end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

     def index
        @scores = Score.all
    end
    
    def new
    @score = Scores.new
    end

    def show
        @score = Score.find(params[:id])
    end
    
    def create
        @score = params[:score]
       @score.save
   # @score.new(params.require(:scores).permit(:score))
   # @score.save
    end
    
     def edit
        @score =  Ship.find(params[:id])
    end
    def update
        @score = Score.find(params[:id])
        if @score.update()
        redirect_to @score
        else
        render 'edit'
        end
    end
        
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_page_helper.rb
module GamePageHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/one_player_helper.rb
module OnePlayerHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/player/new.html.erb
<h2>Second page</h2>

<%= form_for :player, url: player_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :level %><br>
    <%= f.text_area :level %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/players/new.html.erb
  
<body>
  <header>
      <img src="/assets/Title.png" alt="Title" class="title">
    </header>

<main>
    <h1>Enter a Username and Password</h1>
<%= form_for @player do |f| %>

  <p>
    <%= f.label :userName %> 
    <br>
    <%= f.text_field :userName %> 
  </p>

  <div id="submitButton">
    <%= f.submit %>
  </div>

<% end %>

<!--<div>
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %>
      <% end %>
    </div>
    <div>
    <%= yield %>
</div>-->

</main>
</body>

app/views/scores/index.html.erb
<head>
    <%= stylesheet_link_tag "scores.css" %>
    <%= javascript_include_tag "scores.js" %>
</head>

<body>
    <header>
      <img src="/assets/Title.png" alt="Title" class="title">
      <!--475 100-->
    </header>
    
    <main>
    <h1>Top 10 Scores</h1>
    <table>
      <tr>
        <th>Name</th>
        <th>Score</th>
      </tr>
 
      <% nameArr = Array.new%>
      <% scoreArr = Array.new%>
      <% i = 0%>
      <% max = 0%>
      
     <% @scores.each do |score| %>
     <% nameArr[i] = Player.find(score.playerId) %>
     <% scoreArr[i] = score.score %>
     <% i+1 %>
     <% end %>
     
     
     <% scoreArr.sort %>
      
      <% @scores.each do |score| %>
      <% player = Player.find(score.playerId)%>
        <tr>
          <td><%= player.userName %></td>
          <td><%= score.score %></td>
        </tr>
      <% end %>
    </table>
    </main>
</body>

app/views/scores/show.html.erb
<p>
  <strong>Top 10 scores:</strong>
  <%= @score = Score.all %>
</p>
 

<%= link_to 'Back', root_path %>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en">

<!--Header-->
	<head>
		<meta charset="UTF-8">
		<title>PracticeBattleship</title>
		<link rel="stylesheet" type="text/css" href="index.css">
	    <%= stylesheet_link_tag "index.css"%>
        <%= javascript_include_tag "index.js" %>
		<script type="text/javascript" src="index.js"></script>
	</head>

	<body>

		<header>
			<img src="/assets/Title.png" alt="Title" class="title">
			
		</header>

		<br>

	<main>
		
	<audio controls autoplay loop id="backgroundMusic">
  		<source src="/assets/startTheme.mp3" type="audio/mp3">
	</audio>
	<audio>
		<source src="/assets/grid.mp3">
	</audio>
	<audio>
		<source src="/assets/target.mp3">
	</audio>

	</main>

<div id="start">
	<%= link_to 'Start', new_player_path, id: "startButton", class: "fade-inout", onmouseover: "playclip()", onclick: "start()" %>
      <!--<button type="button" onmouseover="playclip(); still();" onclick="start();" id="startButton" class="fade-inout">Start</button>-->
  </div>

  <div id="otherButtons">
      <button type="button" id="optionsButton" onclick="options();">Options</button>
      <%= link_to 'Scores', scores_url, id: "scoresButton", onmouseover: "playclip();" %>
      <!--<button type="button" id="scoresButton">Scores</button>-->
  </div>
  
  	<div id="options">
		<h1>Options</h1>
		<form action="/action_page.php" method="get" id="optionsBox">
  			<input type="checkbox" id="Music" value="Music" onchange="musicToggle(this);">
			<label for="Music">Turn off Music<br></label>
			<input type="checkbox" id="SoundFX" value="SoundFX" onchange="soundFXToggle(this);">
  			<label for="SoundFX">Turn off SoundFX<br></label>
		</form>
		 <button type="button" onclick="hideOptions();createCookie();" id="close">Close</button>
	</div>

	</body>

</html>